- src/main/java/com/interstellarchef/Main.java
- src/main/java/com/interstellarchef/view/View.java
-Adds method to View class to print basic game info
-Adds statement to Main class to run method
> added basic game info, AB#81

- .gitignore
- gradle.properties
- settings.gradle
- updated the gradle project settings, to replace 'replace-me' instances.
> updated gradle settings & project name, AB#80

- src/main/java/com/interstellarchef/Main.java
- src/main/java/com/interstellarchef/controller/GameController.java
Add the game controller class with quitGame, getUserInput, and playGame() methods
> Add GameController class, AB#83

- src/main/java/com/interstellarchef/Main.java
- src/main/java/com/interstellarchef/controller/GameController.java
Add start game method to provide an option to play to start a new game.
> Add startGame class, AB#82

- src/main/java/com/interstellarchef/controller/GameController.java
- src/main/java/com/interstellarchef/controller/TextParser.java
- src/main/java/com/interstellarchef/model/Game.java
-added functionality to move locations, tested in GameController class
> added method to change current location, AB#90

- src/main/java/com/interstellarchef/controller/TextParser.java
- moves prompt string into while loop to continuously prompt user for action input
> Moves 'what would you like to do' string into while loop, AB#86

- src/main/java/com/interstellarchef/controller/TextParser.java
-directs user to enter help to see valid actions
> added response for invalid input, AB#91

- src/main/java/com/interstellarchef/controller/GameController.java
- src/main/java/com/interstellarchef/controller/TextParser.java
- src/main/java/com/interstellarchef/model/Character.java
- src/main/java/com/interstellarchef/model/Game.java
Fulfill look function requirement.
> Look function

- src/main/java/com/interstellarchef/controller/GameController.java
- src/main/java/com/interstellarchef/controller/TextParser.java
> Bug fix, AB#387

- src/main/java/com/interstellarchef/controller/TextParser.java
- src/main/java/com/interstellarchef/model/Location.java
- Updates game to include player status printout
- Includes current location, items in that current location, and available exits.
> Added in Player Status Print out, AB#88

- src/main/resources/items.json
> Add item.json file, AB#97

- src/main/java/com/interstellarchef/controller/GameController.java
- src/main/java/com/interstellarchef/model/Character.java
- src/main/java/com/interstellarchef/model/Monster.java
- src/main/resources/characters.json
- src/main/resources/items.json
- src/main/resources/monsters.json
-Adds monster subclass
-Nests items in json characters
> Load character from json, AB#98

- src/main/java/com/interstellarchef/model/Game.java
- src/main/resources/locations.json
- creates look functionality for inventory, jar-tested
> Look inventory, AB#104

- src/main/resources/locations.json
- minor fixes to missing descriptions
- added `\n` to certain description strings for cleaner print outs to the terminal
> fixed the missing descriptions; cleaned up printouts, AB#94

- src/main/java/com/interstellarchef/controller/TextParser.java
- src/main/java/com/interstellarchef/model/Game.java
- src/main/resources/locations.json
- Add drop [item name] function
> Add drop [item name] function, AB#105

- src/main/java/com/interstellarchef/controller/GameController.java
- src/main/java/com/interstellarchef/controller/TextParser.java
- src/main/java/com/interstellarchef/model/Game.java
- src/main/java/com/interstellarchef/model/GameText.java
- src/main/java/com/interstellarchef/model/Item.java
- src/main/java/com/interstellarchef/model/Location.java
- src/main/java/com/interstellarchef/model/Player.java
- src/main/resources/gametext.json
- src/main/resources/locations.json
- added in 'equip item' logic 
- un-equips currently equipped item, if any, then equips new item
- updated 'help' information to include new commands
> Added logic to equip item & display equipped item, AB#99

- src/main/java/com/interstellarchef/controller/TextParser.java
- src/main/java/com/interstellarchef/model/Character.java
-adds method for receiving item from npc to Character class, jar-tested
> added functionality to receive item from npc, AB#405

- src/main/java/com/interstellarchef/controller/TextParser.java
- src/main/java/com/interstellarchef/model/Character.java
- src/main/java/com/interstellarchef/model/Game.java
-adds prepareToFly() and fly() methods to game class
-allows player to travel to and from planets
> adds discovery pod functionality, AB#405

- src/main/java/com/interstellarchef/controller/TextParser.java
- src/main/java/com/interstellarchef/model/Game.java
- src/main/java/com/interstellarchef/model/GameText.java
- src/main/java/com/interstellarchef/model/Location.java
- src/main/resources/gametext.json
- src/main/resources/locations.json
- adds in working 'which hand' functionality, applicable to any monster in the game 
- Note: will refactor execution logic (picking between the 2 games) when adding in second mini game
> Adds 'Which Hand' mini game for monsters, AB#407

- src/main/java/com/interstellarchef/controller/TextParser.java
- src/main/java/com/interstellarchef/model/Monster.java
- src/main/resources/locations.json
- added in riddles for monsters who would be asking riddles for the mini game instead of 'choose a hand' game
- when a riddle is answered correctly, riddles hashmap is emptied (and monster will not ask riddles again if talked to again)
> Added in Riddle game logic (complete), AB#406

- src/main/java/com/interstellarchef/model/Monster.java
- fixes the use case where player interacts with a monster who has riddles available for the game, but no items to give. 
- monster now taunts the player, playfully.
> Fixes monster w/riddles, but no items bug, AB#417

- src/main/java/com/interstellarchef/Main.java
- src/main/java/com/interstellarchef/controller/GameController.java
- src/main/java/com/interstellarchef/controller/TextParser.java
- src/main/java/com/interstellarchef/model/Character.java
- src/main/java/com/interstellarchef/model/Game.java
- src/main/java/com/interstellarchef/util/GameText.java
- src/main/java/com/interstellarchef/util/Recipe.java
- src/main/java/com/interstellarchef/view/View.java
- src/main/resources/locations.json
- src/main/resources/recipes.json
-handles all communications with the Head Chef
-creates logic to check inventory against recipes
-provides messages for completed recipes and fully completed game
> Complete recipe, AB#409

- src/test/java/com/interstellarchef/MainTest.java
- src/test/java/com/interstellarchef/controller/GameControllerTest.java
- src/test/java/com/interstellarchef/controller/TextParserTest.java
- src/test/java/com/interstellarchef/model/CharacterTest.java
- src/test/java/com/interstellarchef/model/GameTest.java
- src/test/java/com/interstellarchef/model/GameTextTest.java
- src/test/java/com/interstellarchef/model/ItemTest.java
- src/test/java/com/interstellarchef/model/LocationTest.java
- src/test/java/com/interstellarchef/model/MonsterTest.java
- src/test/java/com/interstellarchef/model/PlayerTest.java
- src/test/java/com/interstellarchef/view/ViewTest.java
> Set up test directory for unit testing, AB#406

- src/main/java/com/interstellarchef/model/Character.java
- src/main/java/com/interstellarchef/model/Location.java
- src/test/java/com/interstellarchef/model/CharacterTest.java
-removes recipe items and recipe card from player inventory after recipe is completed and player talks to chef
-adds unit tests for trade() method in Character class
> Recipe Items and trade() tests, AB#409

- src/test/java/com/interstellarchef/model/GameTest.java
- Test get/drop/fly method in unit test
> Game class unit test, AB#103

- src/test/java/com/interstellarchef/model/CharacterTest.java
-fixes assertion error in CharacterTest class
> Fix test, AB#409

- src/main/java/com/interstellarchef/controller/TextParser.java
-checked entire program to ensure all getMonsters are checked for null prior to calling method to prevent null pointer exceptions
> fixed additional null monster exceptions, AB#420
